on: [push, pull_request]

name: CI

jobs:
  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install SQLite
        run: sudo apt-get update && sudo apt-get install libsqlite3-dev

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test
